services:
  ftp:
    image: nobrin/proftpd-sftp
    restart: always
    networks:
      - default
    volumes:
      - ./data:/data
      - ./config:/etc/proftpd/sftp
    ports:
      - 2222:2222
    environment:
      - SFTP_AUTH_METHODS=password
